#!/bin/bash
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# echo "Run prepare-commit-msg"

# Get the current branch name
branch_name=$(git branch --show-current)

# Extract the Jira ticket number
ticket_number=$(echo "$branch_name" | grep -oE '^[a-zA-Z]+-[0-9]+')

# If a valid ticket number is found, use it as a prefix
if [ -n "$ticket_number" ]; then

    prefix="$ticket_number: "

    echo "Found ticket number '$ticket_number', adding prefix '$prefix' to commit message"

    sed -i -e "1s/^/$prefix/" "$COMMIT_MSG_FILE"
fi
