- name: Install workstation packages
  ansible.builtin.package:
    name:
      - gedit

# - name: Install workstation snap packages
#   community.general.snap:
#     name:
#       - mqtt-explorer
#       - drawio
#       - keepassxc
#       - bitwarden
#       - helm
#       - poedit

# kubectl
# os

## desktop environments
- include_tasks: desktop_environments/gnome/media_keys.yml
  when: gnome is defined and gnome == true