# Load distro-specific variables
# - name: Load distro specific variables
#   include_vars: "{{ ansible_distribution }}.yaml"

# setup system
- ansible.builtin.include_tasks: system/flatpak.yaml
- ansible.builtin.include_tasks: system/templates.yaml
- ansible.builtin.include_tasks: system/pipx.yaml
- ansible.builtin.include_tasks: system/fonts.yaml

# setup desktop environment
- name: Included GNOME desktop environment tasks
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/main.yaml
  when: ansible_env.XDG_CURRENT_DESKTOP in ['GNOME', 'Unity']

# install software
# - name: Install software
#   ansible.builtin.include_tasks:
#     file: software/main.yaml
- ansible.builtin.include_tasks: software/tasks/default_package.yaml
- ansible.builtin.include_tasks: software/tasks/virtualbox.yaml
- ansible.builtin.include_tasks: software/tasks/flameshot.yaml
- ansible.builtin.include_tasks: software/tasks/keepassxc.yaml
- ansible.builtin.include_tasks: software/tasks/ms_vs_code.yaml
- ansible.builtin.include_tasks: software/tasks/ms_edge.yaml
- ansible.builtin.include_tasks: software/tasks/firefox.yaml
- ansible.builtin.include_tasks: software/tasks/python.yaml
- ansible.builtin.import_tasks: software/tasks/node.yaml


# Other
- name: Print all available facts for debugging
  ansible.builtin.debug:
    var: ansible_facts

# TEMP only run new stuff
# - name: Software include MS Edge
#   tags: edge
#   ansible.builtin.include_tasks:
#     file: software/tasks/ms_edge.yaml
#     apply:
#       tags: edge

# - name: GNOME extensions
#   tags: new
#   ansible.builtin.include_tasks:
#     file: desktop_environments/gnome/tasks/gnome_extensions.yaml
#     apply:
#       tags: new