# Load distro-specific variables
# - name: Load distro specific variables
#   include_vars: "{{ ansible_distribution }}.yaml"

# - name: Load custom keybindings names
#   ansible.builtin.include_vars: custom_keybindings.yaml
#   when: ansible_env.XDG_CURRENT_DESKTOP in ['GNOME', 'Unity']

# setup system
- name: Include setup Flatpak tasks
  ansible.builtin.include_tasks:
    file: system/flatpak.yaml

- name: Included GNOME desktop environment tasks
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/main.yaml
  when: ansible_env.XDG_CURRENT_DESKTOP in ['GNOME', 'Unity']

# install software
- name: Install software
  ansible.builtin.include_tasks:
    file: software/main.yaml





# - name: Install workstation snap packages
#   community.general.snap:
#     name:
#       - mqtt-explorer
#       - drawio
#       - keepassxc
#       - bitwarden
#       - helm
#       - poedit

# kubectl
# os

# - name: Print all available facts for debugging
#   ansible.builtin.debug:
#     var: ansible_facts