- name: Install workstation packages
  ansible.builtin.package:
    name:
      - gedit

# - name: Install workstation snap packages
#   community.general.snap:
#     name:
#       - mqtt-explorer
#       - drawio
#       - keepassxc
#       - bitwarden
#       - helm
#       - poedit

# kubectl
# os

## desktop environments
- include_tasks: desktop_environments/gnome/main.yaml
  when: ansible_facts['env']['XDG_CURRENT_DESKTOP'] == 'GNOME'

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts