# Load distro-specific variables
# - name: Load distro specific variables
#   include_vars: "{{ ansible_distribution }}.yaml"

- name: Load custom keybindings names
  ansible.builtin.include_vars:
    file: custom_keybindings.yaml
    name: custom_keybindings
  when: ansible_env.XDG_CURRENT_DESKTOP in ['GNOME', 'Unity']

# setup system
- name: Include setup Flatpak tasks
  ansible.builtin.include_tasks:
    file: system/flatpak.yaml

- name: Install pipx
  ansible.builtin.package:
    name: pipx

- name: Included GNOME desktop environment tasks
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/main.yaml
  when: ansible_env.XDG_CURRENT_DESKTOP in ['GNOME', 'Unity']

# install software
- name: Install software
  ansible.builtin.include_tasks:
    file: software/main.yaml

# More font fixes (fixes ugly Flatpak Firefox fonts)
# https://github.com/flatpak/flatpak/issues/4571
- name: Remove ugly X fonts
  ansible.builtin.package:
    name:
      - xfonts-base
      - xfonts-100dp
      - xfonts-75dpi
    state: absent

- name: Copy Template files
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.copy:
    src: "Templates/{{ item }}"
    dest: "$HOME/Templates/{{ item }}"
  with_items:
    - "Excel Sheet.xlsx"
    - "NOTES.md"
    - "README.md"
    - "Powerpoint Presentation.pptx"
    - "Word Document.docx"

# - name: Print all available facts for debugging
#   ansible.builtin.debug:
#     var: ansible_facts