# Load distro-specific variables
# - name: Load distro specific variables
#   include_vars: "{{ ansible_distribution }}.yaml"

# setup system
- ansible.builtin.include_tasks: system/flatpak.yaml
- ansible.builtin.include_tasks: system/pipx.yaml
- ansible.builtin.include_tasks: system/templates.yaml
- ansible.builtin.include_tasks: system/fonts.yaml

# setup desktop environment
- name: Included GNOME desktop environment tasks
  ansible.builtin.include_tasks:
    file: desktop_environment/gnome/main.yaml
  when: ansible_env.XDG_CURRENT_DESKTOP in ['GNOME', 'Unity']

# install apps
- ansible.builtin.include_tasks: apps/default_package.yaml
- ansible.builtin.include_tasks: apps/virtualbox.yaml
- ansible.builtin.include_tasks: apps/flameshot.yaml
- ansible.builtin.include_tasks: apps/keepassxc.yaml
- ansible.builtin.include_tasks: apps/ms_edge.yaml
- ansible.builtin.include_tasks: apps/firefox.yaml

# Install programming
- ansible.builtin.import_tasks: programming/ms_vs_code.yaml
- ansible.builtin.import_tasks: programming/intellij.yaml
- ansible.builtin.import_tasks: programming/python.yaml
- ansible.builtin.import_tasks: programming/java.yaml
- ansible.builtin.import_tasks: programming/node.yaml
- ansible.builtin.import_tasks: programming/rust.yaml


# Other
- name: Print all available facts for debugging
  ansible.builtin.debug:
    var: ansible_facts

# TEMP only run new stuff
# - name: Software include MS Edge
#   tags: edge
#   ansible.builtin.include_tasks:
#     file: software/ms_edge.yaml
#     apply:
#       tags: edge

# - name: GNOME extensions
#   tags: new
#   ansible.builtin.include_tasks:
#     file: desktop_environment/gnome/tasks/gnome_extensions.yaml
#     apply:
#       tags: new