- name: GNOME | keybindings | set custom-keybindings
  become_user: "{{ ansible_env.SUDO_USER }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "{{ custom_keybindings | dict2items | map(attribute='value') | list }}"