- name: GNOME | keybindings | set custom-keybindings
  become_user: "{{ ansible_env.SUDO_USER }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "{{ custom_keybindings | dict2items | map(attribute='value') | map('regex_replace', '^(.*)$', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/\\1/') | list }}"

- name: Set GNOME system monitor shortcut
  become_user: "{{ ansible_env.SUDO_USER }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ custom_keybindings.system_monitor }}/name"
      value: "'Open system monitor'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ custom_keybindings.system_monitor }}/command"
      value: "'gnome-system-monitor'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ custom_keybindings.system_monitor }}/binding"
      value: "'<Primary><Shift>Escape'"