- name: GNOME | touchpad
  become_user: "{{ ansible_env.SUDO_USER }}"
  dconf:
    key: "{{ item.key }}"
    value:  "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
      value: true