scan_timeout = 30   # Timeout for starship to scan files (in milliseconds).
add_newline = false  # Add a new line before the start of the prompt.


# format = "$all"
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "@[$hostname](bold red) in "
trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 3       # The number of parent folders that the current directory should be truncated to.
truncate_to_repo = false    # Whether or not to truncate to the root of the git repo that you're currently in.
format = "[$path]($style)[$read_only]($read_only_style) " # The format for the module.
style = "bold cyan"         # The style for the module.
disabled = false            # Disables the directory module.
read_only = "🔒"             # The symbol indicating current directory is read only.
read_only_style = "red"     # The style for the read only symbol.
truncation_symbol = "../"   # The symbol to prefix to truncated paths. eg: "…/"
home_symbol = "~"           # The symbol indicating home directory.


[env_var]
variable = "PYCUSTOM_CUR_ENV"
default = "unknown env"
format = "[$env_value]($style) "
style = "yellow bold dimmed"


# [character]
# success_symbol = "[➜](bold green) "
# error_symbol = "[✗](bold red) "

# [custom.taskwarrior]
# when = "echo 0"
# command = "task +in count"
# format = "[$symbol($output)]($style) inbox"

# [kubernetes]
# disabled = false