# https://support.mozilla.org/en-US/kb/install-firefox-linux
# https://wiki.debian.org/Firefox

- name: Install firefox dependencies
  ansible.builtin.package:
    name: libdbus-glib-1-2

- name: Download and install firefox
  ansible.builtin.shell:
    chdir: /tmp
    cmd: |
      #!/bin/bash

      # Download and install firefox
      wget \
        --content-disposition \
        'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US'
      tar xjf firefox-*.tar.bz2
      mv firefox /opt
      ln -sf /opt/firefox/firefox /usr/local/bin/firefox
    creates: /opt/firefox

- name: Add firefox desktop shortcut
  ansible.builtin.shell:
    cmd: |
      #!/bin/bash
      wget --quit https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop -P /usr/share/applications
      desktop-file-edit /usr/share/applications/firefox.desktop --set-key=Name --set-value="Firefox (Mozilla build)"
    creates: /usr/share/applications/firefox.desktop

# Set as default browser
# https://wiki.debian.org/DefaultWebBrowser
# update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 200
# update-alternatives --set x-www-browser /opt/firefox/firefox

