- name: Install GNOME terminal
  ansible.builtin.package:
    name:
      - gnome-terminal
    state: present

# Recent GNOME does not have a default terminal shortcut anymore
- name: Set GNOME terminal shortcut
  become_user: "{{ ansible_env.SUDO_USER }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ custom_keybindings.terminal }}/name"
      value: "'Open terminal'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ custom_keybindings.terminal }}/command"
      value: "'gnome-terminal'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ custom_keybindings.terminal }}/binding"
      value: "'<Primary><Alt>t'"

# customize terminal
- name: Install a Gogh GNOME terminal theme
  block:

    - name: Clone Gogh repository
      ansible.builtin.git:
        repo: 'https://github.com/Gogh-Co/Gogh.git'
        dest: /tmp/gogh


    - name: Install the desired theme
      become_user: "{{ ansible_env.SUDO_USER }}"
      ansible.builtin.shell: /tmp/gogh/installs/{{ gogh_theme_name | lower | replace(' ', '-') }}.sh
      args:
        executable: /bin/bash
      environment:
        TERMINAL: gnome-terminal

    - name: Remove Gogh repository
      ansible.builtin.file:
        path: /tmp/gogh
        state: absent

  rescue:
    - name: Remove Gogh repository
      ansible.builtin.file:
        path: /tmp/gogh
        state: absent

