- name: Install KeepassX
  ansible.builtin.package:
    name:
      - keepassxc
      - desktop-file-utils

- name: Check if .desktop file exists
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.stat:
    path: "$HOME/.local/share/applications/org.keepassxc.KeePassXC.desktop"
  register: desktop_file_exists

- name: Install and configure KeePassXC .desktop file
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.shell: |
    desktop-file-install --dir=$HOME/.local/share/applications /usr/share/applications/org.keepassxc.KeePassXC.desktop &&
    desktop-file-edit $HOME/.local/share/applications/org.keepassxc.KeePassXC.desktop --set-key=Exec --set-value="keepassxc -platform xcb %f" &&
    update-desktop-database $HOME/.local/share/applications
  when: not desktop_file_exists.stat.exists



# - name: Check if keys are already set in org.keepassxc.KeePassXC.desktop file
#   ansible.builtin.shell: >
#     grep -q 'Exec=keepassxc -platform xcb %f' /usr/share/applications/org.keepassxc.KeePassXC.desktop ||
#     grep -q 'TryExec=keepassxc -platform xcb' /usr/share/applications/org.keepassxc.KeePassXC.desktop
#   changed_when: false
#   ignore_errors: true
#   register: keepassxc_dekstop_file_keys_already_set

# - name: Update org.keepassxc.KeePassXC.desktop.desktop file if keys are not already set
#   ansible.builtin.command: >
#     desktop-file-edit
#       org.keepassxc.KeePassXC.desktop
#       --set-key=Exec --set-value="keepassxc -platform xcb %f"
#       --set-key=TryExec --set-value="keepassxc -platform xcb"
#   when: keepassxc_dekstop_file_keys_already_set.rc != 0
#   become: yes


# I can't find a way to edit the KeepassXC .desktop file

# using nano -> can't find app anymore
# using desktop-file-edit -> can't find app anymore
# copy to .local/share/applications -> can't find app anymore ???
# copy and using different name -> can't find app anymore ??
# copy and using different filename -> can only find original launcher



# Exec=QT_QPA_PLATFORM=xcb keepassxc %f
# TryExec=QT_QPA_PLATFORM=xcb keepassxc

# THIS WORKS
# Exec=env QT_QPA_PLATFORM=xcb keepassxc %f
# TryExec=keepassxc


# desktop-file-install --dir=$HOME/.local/share/applications /usr/share/applications/org.keepassxc.KeePassXC.desktop

# desktop-file-edit $HOME/.local/share/applications/org.keepassxc.KeePassXC.desktop --set-key=Exec --set-value="keepassxc -platform xcb %f"

# update-desktop-database ~/.local/share/applications -v