- name: Load custom keybindings names
  ansible.builtin.include_vars:
    file: custom_keybindings.yaml
    name: custom_keybindings

- name: GNOME desktop environment media keys
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/media_keys.yaml

- name: GNOME desktop environment custom keybindings
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/custom_keybindings.yaml

- name: GNOME desktop environment GNOME terminal
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/gnome_terminal.yaml

- name: GNOME desktop environment Gedit
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/gedit.yaml

- name: GNOME filemanager
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/filemanager.yaml

- name: Set general GNOME dconf settings
  become_user: "{{ ansible_env.SUDO_USER }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    # GNOME desktop
    - key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"
    - key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
      value: "true"
    - key: "/org/gnome/desktop/calendar/show-weekdate"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-show-weekday"
      value: "true"
    - key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
    - key: "/org/gnome/desktop/interface/show-battery-percentage"
      value: "true"
    - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
      value: "true"
    # GNOME shell
    - key: "/org/gnome/shell/weather/automatic-location"
      value: "true"
    # GNOME window manager
    - key: "/org/gnome/desktop/wm/keybindings/show-desktop"
      value: ['<Super>d']
    - key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "':minimize,maximize,close'"
    # GNOME settings-daemon
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
      value: "3700"

# GNOME extensions
- name: GNOME extensions
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/gnome_extensions.yaml