- name: GNOME desktop environment media keys
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/media_keys.yaml

- name: GNOME desktop environment custom keybindings
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/custom_keybindings.yaml

- name: GNOME desktop environment window manager
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/window_manager.yaml


# org/gnome/desktop/interface
- name:
  become_user: "{{ ansible_env.SUDO_USER }}"
  dconf:
    key: "{{ item.key }}"
    value:  "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"

# Nautilus
- name:
  become_user: "{{ ansible_env.SUDO_USER }}"
  dconf:
    key: "{{ item.key }}"
    value:  "{{ item.value }}"
  with_items:
    - key: "/org/gnome/nautilus/preferences/default-folder-viewer"
      value: "'list-view'"
    - key: "/org/gnome/nautilus/list-view/use-tree-view"
      value: "true"
    - key: "/org/gtk/gtk4/settings/file-chooser/sort-directories-first"
      value: "true"
    - key: "/org/gnome/nautilus/preferences/show-create-link"
      value: "true"
    - key: "/org/gnome/nautilus/preferences/show-delete-permanently"
      value: "true"
    - key: "/org/gnome/nautilus/icon-view/captions"
      value: "['size', 'none', 'none']"