- name: GNOME desktop environment media keys
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/media_keys.yaml

- name: GNOME desktop environment custom keybindings
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/custom_keybindings.yaml

- name: GNOME desktop environment window manager
  ansible.builtin.include_tasks:
    file: desktop_environments/gnome/tasks/window_manager.yaml


# org/gnome/desktop/interface
- name: 
  become_user: "{{ ansible_env.SUDO_USER }}"
  dconf:
    key: "{{ item.key }}"
    value:  "{{ item.value }}"
  with_items:
    - key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"