- name: Install Flatpak
  ansible.builtin.package:
    name:
      - flatpak
      - gnome-software-plugin-flatpak

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
