# Homeshick
- name: Install Docker Debian
  tags: minimal,homeshick
  block:
  - name: Install Homeshick
    become_user: "{{ ansible_env.SUDO_USER }}"
    ansible.builtin.git:
      repo: https://github.com/andsens/homeshick.git
      dest: $HOME/.homesick/repos/homeshick
  - name: Clone Homeshick dotfiles repo
    become_user: "{{ ansible_env.SUDO_USER }}"
    ansible.builtin.git:
      repo: https://github.com/bremme/dotfiles.git
      dest: $HOME/.homesick/repos/dotfiles
  - name: Link Homeshick dotfiles
    become_user: "{{ ansible_env.SUDO_USER }}"
    ansible.builtin.shell:
      cmd: $HOME/.homesick/repos/homeshick/bin/homeshick link dotfiles --batch --force
      creates: $HOME/.link-dotfiles-has-run