- ansible.builtin.import_tasks: docker.yaml
- ansible.builtin.import_tasks: folders.yaml
- ansible.builtin.import_tasks: homeshick.yaml
- ansible.builtin.import_tasks: packages.yaml
- ansible.builtin.import_tasks: shell.yaml
