- name: Install base packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - bash-completion
      - build-essential
      - bzip2
      - command-not-found
      - curl
      - fzf
      - git
      - htop
      - jq
      - neofetch
      - rsync
      - tar
      - tree
      - wget
      - zsh

# - name: Install snap packages
#   community.general.snap:
#     name:
#       - yq
#       - starship

# - import_tasks: software/homeshick.yaml





