- name: Install base packages
  ansible.builtin.package:
    name:
      - zsh
      - git
      - wget
      - curl
      - command-not-found
      - htop
      - jq
      - neofetch
      - tree
      - fzf
      - apt-transport-https
      - rsync
      - tar
      - bzip2
      - build-essential

- name: Install snap packages
  community.general.snap:
    name:
      - yq
      - starship

- import_tasks: software/homeshick.yaml





