- name: Install multiple packages
  ansible.builtin.package:
    name:
      - dconf-editor
      - gimp
      - gparted
      - jstest-gtk
      - libreoffice
      - meld
      - sqlitebrowser
      - vlc
      - filezilla
      - darktable
      - gdmap
      - android-sdk-platform-tools
      - timeshift

- name: Remove unnessecary packages
  ansible.builtin.package:
    name:
      - shotwell
      - xterm
    state: absent

- name: Install restricted extra's on Debian
  ansible.builtin.apt:
    name:
    # Install restricted-extras
    - ttf-mscorefonts-installer
    - rar
    - unrar
    - libavcodec-extra
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-vaapi
    # Microsoft Fonts Compatibility
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea

# install as user??
- name: Install multiple Flatpak packages
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - com.jgraph.drawio.desktop
      - com.emqx.MQTTX
      - net.poedit.Poedit
      - org.telegram.desktop
      - org.signal.Signal
      - com.discordapp.Discord
      - com.github.IsmaelMartinez.teams_for_linux
      - io.missioncenter.MissionCenter
    state: present

- name: Install snap packages
  community.general.snap:
    name: keep-presence

# Install dowloadable .deb
# VS Code
# Syncthing

# Install AppImage' s
# Cura

# Install tar.gz
# Camunda modeller