# https://support.mozilla.org/en-US/kb/install-firefox-linux
# https://wiki.debian.org/Firefox

# - name: Install Firefox Flatpak
#   community.general.flatpak:
#     name:
#       - org.mozilla.firefox

# Install firefox from mozilla.org #####################################################
- name: Install firefox dependencies
  tags: firefox
  ansible.builtin.package:
    name: libdbus-glib-1-2

- name: Download and install firefox
  tags: firefox
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.shell:
    chdir: /tmp
    cmd: |
      #!/bin/bash

      # Download and install firefox
      wget \
        --content-disposition \
        'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US'
      tar xjf firefox-*.tar.bz2
      mv firefox $HOME/apps
      ln -sf $HOME/apps/firefox/firefox /$HOME/bin/firefox
    creates: $HOME/apps/firefox

- name: Add firefox desktop shortcut
  tags: firefox
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.shell:
    cmd: |
      #!/bin/bash
      wget --quiet https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop -P $HOME/.local/share/applications
      desktop-file-edit $HOME/.local/share/applications/firefox.desktop --set-key=Name --set-value="Firefox (Mozilla build)"
      # TODO untested
      if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        desktop-file-edit $HOME/.local/share/applications/firefox.desktop --set-key=Exec --set-value="env MOZ_ENABLE_WAYLAND=1 $HOME/apps/firefox/firefox %u"
        desktop-file-edit $HOME/.local/share/applications/firefox.desktop --set-key=Icon --set-value="$HOME/apps/firefox/browser/chrome/icons/default/default128.png"
      fi
    creates: $HOME/.local/share/applications/firefox.desktop

# Firefox about:config #################################################################




# TODO add systemd env variables -> should be loaded for all Wayland sessions
# ~/.config/environment.d/envvars.conf
#

# Set as default browser
# https://wiki.debian.org/DefaultWebBrowser
# update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 200
# update-alternatives --set x-www-browser /opt/firefox/firefox

# about:config
# media.ffmpeg.vaapi.enabled = true
# browser.tabs.insertAfterCurrent = true


# Firefox PWA
# # Install required packages for third-party repositories
# sudo apt update
# sudo apt install debian-archive-keyring # Debian-only
# sudo apt install curl gpg apt-transport-https

# # Import GPG key and enable the repository
# curl -fsSL https://packagecloud.io/filips/FirefoxPWA/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/firefoxpwa-keyring.gpg > /dev/null
# echo "deb [signed-by=/usr/share/keyrings/firefoxpwa-keyring.gpg] https://packagecloud.io/filips/FirefoxPWA/any any main" | sudo tee /etc/apt/sources.list.d/firefoxpwa.list > /dev/null

# # Refresh repositories and install the package
# sudo apt update
# sudo apt install firefoxpwa