- name: Install multiple packages
  ansible.builtin.package:
    name:
      - libreoffice
      - hunspell-nl

# TODO way to synchronise settings
# View -> User Interface
# Tabbed

# View -> Rulers
# Vertical ruler

# Tools -> Options -> View
# Icon Theme: Colibre